//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consulta
    {
        public int protocolo { get; set; }
        public System.DateTime data_hora { get; set; }
        public int id_tipoexame { get; set; }
        public int id_paciente { get; set; }
    
        public virtual paciente paciente { get; set; }
        public virtual tipoexame tipoexame { get; set; }
    }
}
