//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDIntelectahEntities1 : DbContext
    {
        public BDIntelectahEntities1()
            : base("name=BDIntelectahEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<consulta> consultas { get; set; }
        public virtual DbSet<exame> exames { get; set; }
        public virtual DbSet<paciente> pacientes { get; set; }
        public virtual DbSet<tipoexame> tipoexames { get; set; }
    }
}
